using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Text;
using WcfClient.myWcfReferences;//similar to web services
//Apps will add service reference for WCF components to be used in their client application.The service reference creates a Proxy class whose object is used to call the methods to the WCF Component
namespace WcfClient
{
    class Program
    {
        static void Main(string[] args)
        {
            //The proxy class that is generated by the WCF will be the name of the interface suffixed with client.

            //InsertCustomer();
            ReadAllCustomers();
            Console.WriteLine("Press Any Key");
            Console.ReadKey();

        }

        private static void InsertCustomer()
        {
            SportServiceClient proxy = new SportServiceClient();
            try
            {
                proxy.RegisterUser(new Customer

                {
                    Name = "Rahul",
                    ContactNo = 123456
                });// U should add ID if the DB does not have identity set up 

            }

            catch (FaultException fx)
            {
                Console.WriteLine(fx.Message);
            }
            catch (CommunicationException ex)
            { Console.WriteLine(ex.Message); }
            catch (Exception genEx)
            { Console.WriteLine(genEx.Message); }
        }


        private static void ReadAllCustomers()
        {
            var proxy = new SportServiceClient();
            var data = proxy.GetAllCustomers();
            foreach (var cst in data)
                Console.WriteLine(cst.Name + " has paid " + cst.Fees);
        }
    }

}
